<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| PRODUCTION Configuration Template
|--------------------------------------------------------------------------
|
| This is a template for production environment configuration.
| Copy the relevant settings to your config.php file and update with
| your actual production values.
|
| ⚠️ IMPORTANT SECURITY NOTES:
| 1. Change the encryption_key to a unique 32-character string
| 2. Set base_url to your actual domain (with HTTPS)
| 3. Disable all debugging features
| 4. Use secure session settings
|
*/

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|   https://yourdomain.com/
|
| IMPORTANT: Always use HTTPS in production!
|
*/
$config['base_url'] = 'https://yourdomain.com/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
| In production with .htaccess, this should be empty to remove index.php
| from URLs.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
*/
$config['uri_protocol'] = 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/userguide3/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
*/
$config['language'] = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Keep this FALSE in production for SEO-friendly URLs
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|   0 = Disables logging, Error logging TURNED OFF
|   1 = Error Messages (including PHP errors)
|   2 = Debug Messages
|   3 = Informational Messages
|   4 = All Messages
|
| ⚠️ PRODUCTION: Set to 1 (errors only) to avoid filling logs
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
*/
$config['log_path'] = APPPATH . 'logs/';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
*/
$config['cache_path'] = APPPATH . 'cache/';

/*
|--------------------------------------------------------------------------
| Cache Query String
|--------------------------------------------------------------------------
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| ⚠️ CRITICAL SECURITY SETTING!
|
| If you use the Encryption class, you must set an encryption key.
| Generate a UNIQUE 32-character random string for production!
|
| NEVER use the default key or commit your production key to version control!
|
| Generate new key with:
| - PHP: bin2hex(random_bytes(16))
| - Online: https://www.random.org/strings/
| - Command: openssl rand -hex 16
|
*/
$config['encryption_key'] = 'YOUR_UNIQUE_32_CHAR_PRODUCTION_KEY_HERE';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| ⚠️ PRODUCTION SECURITY SETTINGS
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'insurance_erp_session';
$config['sess_expiration'] = 7200; // 2 hours
$config['sess_save_path'] = sys_get_temp_dir(); // Or: APPPATH . 'cache/sessions/';
$config['sess_match_ip'] = TRUE;  // Extra security: match IP address
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = TRUE; // Destroy old session on regeneration

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| ⚠️ PRODUCTION: Set secure and httponly to TRUE when using HTTPS
|
*/
$config['cookie_prefix']    = 'erp_';
$config['cookie_domain']    = ''; // Leave empty or set to '.yourdomain.com'
$config['cookie_path']      = '/';
$config['cookie_secure']    = TRUE;  // ⚠️ Must be TRUE for HTTPS
$config['cookie_httponly']  = TRUE;  // ⚠️ Protection against XSS
$config['cookie_samesite']  = 'Lax'; // CSRF protection

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| ⚠️ DEPRECATED: Do not enable global XSS filtering.
| Filter input in your controllers using $this->input->post(NULL, TRUE)
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
|
| ⚠️ PRODUCTION SECURITY: Enable CSRF protection
|
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'erp_csrf_token';
$config['csrf_cookie_name'] = 'erp_csrf_cookie';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array('api/*'); // Exclude API endpoints if needed

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| ⚠️ PRODUCTION: Enable compression to improve performance
| Note: If you enable this, disable compression in .htaccess to avoid conflicts
|
*/
$config['compress_output'] = FALSE; // Use .htaccess compression instead

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'utc' or 'local'
|
*/
$config['time_reference'] = 'utc';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy (CloudFlare, Load Balancer, etc.),
| you must whitelist the proxy IP addresses from which CodeIgniter should
| trust headers such as HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP.
|
*/
$config['proxy_ips'] = '';

/*
|--------------------------------------------------------------------------
| APPLICATION-SPECIFIC SETTINGS
|--------------------------------------------------------------------------
*/

/*
| Company Information (Can be moved to database in production)
*/
$config['company_name'] = 'Your Insurance Company';
$config['company_email'] = 'info@yourdomain.com';
$config['company_phone'] = '+971-XX-XXXXXXX';
$config['company_address'] = 'Your Address, Dubai, UAE';

/*
| Application Settings
*/
$config['app_version'] = '1.0.0';
$config['app_timezone'] = 'Asia/Dubai'; // UAE timezone
$config['date_format'] = 'd/m/Y'; // DD/MM/YYYY (UAE standard)
$config['time_format'] = 'H:i:s'; // 24-hour format
$config['datetime_format'] = 'd/m/Y H:i:s';

/*
| Financial Settings
*/
$config['currency'] = 'AED';
$config['currency_symbol'] = 'AED';
$config['vat_rate'] = 5; // UAE VAT rate: 5%
$config['decimal_places'] = 2;

/*
| Upload Settings
*/
$config['upload_path'] = './uploads/';
$config['max_upload_size'] = 10240; // 10MB in KB
$config['allowed_file_types'] = 'jpg|jpeg|png|gif|pdf|doc|docx|xls|xlsx';

/*
| Pagination Settings
*/
$config['per_page'] = 25;
$config['num_links'] = 5;

/*
| Backup Settings
*/
$config['backup_path'] = './uploads/backups/';
$config['auto_backup'] = TRUE;
$config['backup_frequency'] = 'daily'; // daily, weekly, monthly

/*
| Email Settings (if using PHP mail or external SMTP)
*/
$config['email_from'] = 'noreply@yourdomain.com';
$config['email_from_name'] = 'Insurance ERP System';

/*
| Security Settings
*/
$config['password_min_length'] = 8;
$config['password_require_uppercase'] = TRUE;
$config['password_require_lowercase'] = TRUE;
$config['password_require_numbers'] = TRUE;
$config['password_require_special'] = TRUE;
$config['max_login_attempts'] = 5;
$config['lockout_duration'] = 900; // 15 minutes in seconds
$config['session_timeout_warning'] = 300; // Show warning 5 minutes before expiry

/*
| API Settings (if using API)
*/
$config['api_enabled'] = FALSE;
$config['api_rate_limit'] = 100; // Requests per hour
$config['api_key_length'] = 32;

/*
|--------------------------------------------------------------------------
| PRODUCTION CHECKLIST
|--------------------------------------------------------------------------
|
| Before deploying to production, ensure:
|
| ✅ Set base_url to your actual domain (HTTPS)
| ✅ Generate unique encryption_key
| ✅ Set log_threshold to 1 (errors only)
| ✅ Enable CSRF protection
| ✅ Set cookie_secure and cookie_httponly to TRUE
| ✅ Update company information
| ✅ Configure email settings
| ✅ Test all functionality
| ✅ Update database credentials in database.php
| ✅ Set proper file permissions (uploads, cache, logs)
| ✅ Enable SSL certificate
| ✅ Test backup and restore functionality
|
*/
